#!/usr/bin/env bash
# Render the Homebrew formula for akiojin/tap from a release SHA256SUMS file.
# Usage: render-homebrew-formula.sh <version> <SHA256SUMS> [download-base-url]
#   download-base-url defaults to https://github.com/akiojin/unity-cli/releases/download/v<version>
set -euo pipefail

if [[ $# -lt 2 ]]; then
  echo "usage: $0 <version> <SHA256SUMS> [download-base-url]" >&2
  exit 2
fi

version="${1#v}"
sums_file="$2"
base_url="${3:-https://github.com/akiojin/unity-cli/releases/download/v${version}}"

sha_for() {
  local asset="$1" sha
  sha="$(awk -v name="${asset}" '{ f = $2; sub(/^\*/, "", f); if (f == name) { print tolower($1); exit } }' "${sums_file}")"
  if [[ ! "${sha}" =~ ^[0-9a-f]{64}$ ]]; then
    echo "error: ${sums_file} has no valid sha256 for ${asset}" >&2
    exit 1
  fi
  printf '%s' "${sha}"
}

osx_arm64="$(sha_for unity-cli-osx-arm64)"
osx_x64="$(sha_for unity-cli-osx-x64)"
linux_arm64="$(sha_for unity-cli-linux-arm64)"
linux_x64="$(sha_for unity-cli-linux-x64)"

cat <<RUBY
# Generated by scripts/release/render-homebrew-formula.sh in akiojin/unity-cli.
class UnityCli < Formula
  desc "Rust CLI for Unity Editor automation over the Unity TCP protocol"
  homepage "https://github.com/akiojin/unity-cli"
  version "${version}"
  license "MIT"

  on_macos do
    on_arm do
      url "${base_url}/unity-cli-osx-arm64"
      sha256 "${osx_arm64}"
    end
    on_intel do
      url "${base_url}/unity-cli-osx-x64"
      sha256 "${osx_x64}"

      # Intel macOS loads ONNX Runtime dynamically for reference embeddings.
      depends_on "onnxruntime"
    end
  end

  on_linux do
    on_arm do
      url "${base_url}/unity-cli-linux-arm64"
      sha256 "${linux_arm64}"
    end
    on_intel do
      url "${base_url}/unity-cli-linux-x64"
      sha256 "${linux_x64}"
    end
  end

  def install
    bin.install Dir["unity-cli-*"].first => "unity-cli"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/unity-cli --version")
  end
end
RUBY
