#!/usr/bin/env python3
"""Generate the Bridge's reserved-name list from the CLI catalog (no manual duplicate list)."""
import argparse
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / 'UnityCliBridge/Packages/unity-cli-bridge/Editor/Tools/BuiltinToolNames.cs'


def render():
    source = (ROOT / 'src/tooling/tool_catalog.rs').read_text()
    block = re.search(r'pub const TOOL_NAMES:.*?= &\[(.*?)\];', source, re.S).group(1)
    names = re.findall(r'"([a-z][a-z0-9_]*)"', block)
    if not names or len(names) != len(set(names)):
        raise ValueError('TOOL_NAMES must be nonempty and unique')
    return ('// Generated by scripts/generate-builtin-tool-names.py. Do not edit.\n'
            '// Includes CLI-local tools, which custom Editor methods must not shadow.\n'
            'namespace UnityCliBridge.Tools\n{\n'
            '    internal static class BuiltinToolNames\n    {\n'
            '        internal static readonly string[] Names =\n        {\n'
            + ''.join(f'            "{name}",\n' for name in names)
            + '        };\n    }\n}\n')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text() != expected:
            parser.exit(1, 'Reserved tool names are stale; run scripts/generate-builtin-tool-names.py\n')
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(expected)
